# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-25 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_siteconfiguration_require_account_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='theme_scss_path',
            field=models.CharField(help_text=b'DEPRECATED: THIS FIELD WILL BE REMOVED!', max_length=255, verbose_name='Path to custom site theme'),
        ),
    ]
