# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-25 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20170525_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
        ),
        migrations.AlterUniqueTogether(
            name='siteconfiguration',
            unique_together=set([]),
        ),
    ]
