# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-26 10:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_siteconfiguration_optimizely_snippet_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_sailthru',
            field=models.BooleanField(default=False, help_text='Determines if purchases should be reported to Sailthru.', verbose_name='Enable Sailthru Reporting'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='theme_scss_path',
            field=models.CharField(help_text=b'DEPRECATED: THIS FIELD WILL BE REMOVED!', max_length=255, verbose_name='Path to custom site theme'),
        ),
        migrations.AlterUniqueTogether(
            name='siteconfiguration',
            unique_together=set([]),
        ),
    ]
