# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-25 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20170525_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='enable_sailthru',
            field=models.BooleanField(default=False, help_text='Determines if purchases should be reported to Sailthru.', verbose_name='Enable Sailthru Reporting'),
        ),
    ]
